### ISSUE TITLE
Boot/Installation in VMware Workstation 17 Pro - Extremely Slow

### ISSUE THREAD

**Issue by Rtype-SPC** [Vanilla-OS/os#45]
Hi,
ISO Stable: VanillaOS-22.10-all.20221229

Boot and installation process in VMware Workstation 17 Pro (17.0.0 build-20800274)

Extremely Slow/Inusable.

Need a some type of configuration on boot?

Thanks.

**Comment by kbdharun** [comment]
> Hi,
> ISO Stable: VanillaOS-22.10-all.20221229
> 
> Boot and installation process in VMware Workstation 17 Pro (17.0.0 build-20800274)
> 
> Extremely Slow/Inusable.
> 
> Need a some type of configuration on boot?
> 
> Thanks.

 Disable 3d acceleration. And try the Installation process. If window resolution isn't fine go to displays under settings and update it. And after install in the first setup select the option to install open-vm tools. After that you will have a seamless experience hopefully.

**Comment by Rtype-SPC** [comment]
> > Hi,
> > ISO Stable: VanillaOS-22.10-all.20221229
> > Boot and installation process in VMware Workstation 17 Pro (17.0.0 build-20800274)
> > Extremely Slow/Inusable.
> > Need a some type of configuration on boot?
> > Thanks.
> 
> Disable 3d acceleration. And try the Installation process. If window resolution isn't fine go to displays under settings and update it. And after installation in the first setup select the option to install open-vm tools. After that you will have a seamless experience hopefully.

Work fine !
Thanks !!

**Comment by kbdharun** [comment]
> Work fine ! Thanks !!

Glad it works :)

**Comment by rudydevolder** [comment]
I also had problems with the resolution, but I didn't have to disable the 3d acceleration because it was disabled by default. Probably because when I started to configure the virtual machine in VMWare I choose for a Linux machine with Kernel 5.x instead of Ubuntu.

**Comment by rudydevolder** [comment]
I think I did the installation from the VMWare tools right, but I can't copy paste text from outside Vanilla in my in my console.

**Comment by kbdharun** [comment]
> I think I did the installation from the VMWare tools right, but I can't copy paste text from outside Vanilla in my in my console.

Did you go through first-setup and install openvm-tools?

**Comment by rudydevolder** [comment]
Yes, I even started first-setup again. But because I saw nothing happening, I tried some other things like mounting the CD and going to bash to install the software but this gave me the error that it was already installed.

**Comment by kbdharun** [comment]
> Yes, I even started first-setup again. But because I saw nothing happening, I tried some other things like mounting the CD and going to bash to install the software but this gave me the error that it was already installed.

Can you try this and let me know if it works?

`sudo abroot exec apt install open-vm-tools-desktop` then reboot and see if it works. I think we missed it since it's an [optional package](https://docs.vmware.com/en/VMware-Tools/12.1.0/com.vmware.vsphere.vmwaretools.doc/GUID-8B6EA5B7-453B-48AA-92E5-DB7F061341D1.html). If it works for you I will add it back.

**Comment by rudydevolder** [comment]
YEAH, IT WORKS!!! Thanks mate 🥇

**Comment by kbdharun** [comment]
> YEAH, IT WORKS!!! Thanks mate 🥇

Thanks for helping me out, Will add it now to the package.
