### ISSUE TITLE
VSO tasks not running on boot

### ISSUE THREAD

**Issue by SamuelNorbury** [Vanilla-OS/os#89]
### Issue Description

![image](https://user-images.githubusercontent.com/2980566/212465543-b09f40d3-23e9-4d96-b550-522f653509eb.png)

The above task was created to automatically start syncthing, installed via apx, on boot. However, it never gets started.

### Steps to Reproduce

```
$ apx install syncthing
$ vso create-task -n "Syncthing" -d "start syncthing on boot" --on-boot -c "apx run syncthing"
$ reboot
```

after boot: 
```
$ pgrep syncthing
```

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
--on-boot is not implemented and should not even be available
